name: pillmate
description: "PillMate - Medication Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  shared_preferences: ^2.3.2
  audioplayers: ^6.0.0
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  min_sdk_android: 21

  # افصل الصور لكل منصة
  image_path_android: "assets/images/logo10.png"
  image_path_ios: "assets/images/logo10.png"

  # Android adaptive icon
  adaptive_icon_foreground: "assets/images/logo10.png"
  adaptive_icon_background: "#0B446B"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/Frame.svg
    - assets/images/Frame2.svg
    - assets/images/Group.svg
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/emergency.png
    - assets/images/Untitled-3-01.png
    - assets/audio/
    - assets/translations/
